import feladatok

szokoz: int = feladatok.feladat1("Csak az Avenged Sevenfold")
print(f"Ennyi db szóköz van a szövegben: {szokoz}")

szokoz_nelkul:int = feladatok.feladat2("Csak a wow a jövőben")
print(szokoz_nelkul)

kisbetus:int = feladatok.feladat3("Szandi és a 4/16-os stat")
print(kisbetus)
print("\n")
hettel_oszthato:int = feladatok.hazi1()
print(f"Ennyi 7-tel osztható szám van: {hettel_oszthato}")
print("\n")
tizenkettovel_oszthato: int = feladatok.hazi2()
print(f"Ennyi 12-vel osztható szám van: {tizenkettovel_oszthato}")
print("\n")
elsohusz: int = feladatok.hazi3()
print(f"A 20 3-mal osztható szám négyzetének összege: {elsohusz}")
print("\n")
oszto: int = feladatok.hazi4(150)
print(f"A szám egész osztói: {oszto}")
print("\n")
legnagyobb: int = feladatok.hazi5(12)
print(f"A legnagyobb osztó: {legnagyobb}")